†source 'http://rubygems.org'

gem 'rails', '4.1.0'
#gem 'rails', '3.0.3'
gem 'sqlite3'
#gem 'sqlite3-ruby', '1.2.5', :require => 'sqlite3'
gem 'nifty-generators'
gem 'mocha', :group => :test

gem "rmagick"

gem "carrierwave"

gem 'better_errors', '~> 2.1.1'

gem "binding_of_caller"
